### ISSUE TITLE
Target v0.3.0 Release

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#424]
This issue is to target a v0.3.0 release for June 16, with a boptest-service sync for June 30.  Targeted completions include (to be updated):

- [x] Issue #73 for standardizing testcase.py API and improving messaging to users 
- [x] Issue #403 for adding API to submit results to dashboard
- [x] Issue #423 for resource file exclusion list
- [x] Issue #418 for improved documentation of multizone_office_simple_air test case
- [x] Issue #214 for webpage.
- [x] Issue https://github.com/ibpsa/project1-boptest/issues/406 for Spawn support
- [x] Issue https://github.com/ibpsa/project1-boptest/issues/450 for unit test improvement
- [x] Issue https://github.com/ibpsa/project1-boptest/issues/445 for related Service update
- [x] Issue https://github.com/ibpsa/project1-boptest/issues/448 for related Service update
- [ ] Issue https://github.com/ibpsa/project1-boptest/issues/431 for dashboard revision
