### ISSUE TITLE
Update signal exchange block

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#49]
This issue corresponds to the updating of the signal exchange block in https://github.com/ibpsa/modelica-ibpsa/issues/1059 to:

- [x] Enumerate the KPI parameter (see also https://github.com/ibpsa/project1-boptest/issues/57)
- [x] Add a description parameter of the signal (see also https://github.com/ibpsa/project1-boptest/issues/37)
- [x] Add min/max (see also https://github.com/ibpsa/project1-boptest/issues/41)
- [x] Verify correct operation when 1059 merged to ibpsa-modelica master.  One issue will be change in parameter name ``Description`` to ``description``.

**Comment by JavierArroyoBastida** [comment]
@dhblum and @mwetter, 
The enumeration of the KPI signals has been merged in https://github.com/ibpsa/modelica-ibpsa/pull/1116. So far we are using entries for power and energy because we wanted the emulator developer to decide where to integrate: in the model or in the KPI calculator in python. However, I find that misleading and prone to errors in the tagging and the KPI calculation processes. 
For instance the computation of cost and emissions requires power signals since prices and emission factors can vary over time whereas with an energy signal the information of when the energy was consumed is lost.
What do you think? should I leave the energy signals out and compute everything from powers?

**Comment by mwetter** [comment]
It probably is better to consistently integrate all power outside of the Modelica model (I assume this is what you prefer) and hence remove the option to declare energy.

If there is a strong case to have energy as a KPI indicator in Modelica, then we can add it later. It is easier to add features than removing (and breaking models that rely on the feature).

**Comment by dhblum** [comment]
I agree with Michael on this.

**Comment by dhblum** [comment]
Enumeration looks good.  One thing is that in Aachen, @icupeiro mentioned that he may still like to keep the ability to tag multiple keywords to a signal (as before, the tagging was a comma-delimited list in a string parameter).  Although, I can't think of a use case for this anymore. @icupeiro, what would be your use case?  The KPI tags so far are:
```
 type SignalsForKPIs = enumeration(
    None
      "Not used for KPI",
    ZoneTemperature
      "Zone temperature",
    ElectricPower
      "Electric power from grid",
    DistrictHeatingPower
      "Thermal power from district heating",
    GasPower
      "Thermal power from natural gas",
    BiomassPower
      "Thermal power from biomass",
    SolarThermalPower
      "Thermal power from solar thermal",
    Water
      "Water") "Signals used for the calculation of key performance indicators";
```

**Comment by mwetter** [comment]
`ZoneTemperature` should be made clear as it can be air, radiative or operative temperature.
Relative humidity may also need to be added (to compute thermal comfort).
For `Water`, it is not clear if this is WaterFlowRate or the time integral of it. Moreover, we should distinguish `FreshWater` and `GreyWater`, or use for now only `FreshWater` so we can later add `GreyWater`.

**Comment by dhblum** [comment]
Thanks Michael.  Also CO2 for IAQ as discussed in Aachen.

**Comment by JavierArroyoBastida** [comment]
So that makes:

AirZoneTemperature
RadiativeZoneTemperature
OperativeZoneTemperature
RelativeHumidity
CO2Concentration
ElectricPower
DistrictHeatingPower
GasPower
BiomassPower
SolarThermalPower
FreshWaterFlowRate

Please confirm or suggest further changes and I'll make another pull request.

@dhblum and @icupeiro, I can't think of any case where it's required to tag more than one keyword to a signal. Actually I think that's not possible: a signal can be of only one type. For instance it could be either electric power or water, but they are mutually exclusive so cannot be both at the same time. It is then up to the KPI calculator to use the signals that are required for a specific KPI.

**Comment by dhblum** [comment]
In this commit https://github.com/ibpsa/modelica-ibpsa/commit/e51759a6d82a209619f42a4d026c0c4c9c5eaf57 I suggested a None type so that the Read block can be defaulted to having no KPI specified.

**Comment by icupeiro** [comment]
In principle I was thinking in a main tag 'power' and a sub-tag 'gas', 'biomass', 'solarthermal', etc... but with this kind of tagging the problem is solved

**Comment by dhblum** [comment]
Ok thanks.  In the future, we may consider sub-tags, particularly for adding more meta-data to the signals.

**Comment by dhblum** [comment]
Fourth task implemented by https://github.com/ibpsa/project1-boptest/pull/93.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/96 and https://github.com/ibpsa/modelica-ibpsa/pull/1170.
