### ISSUE TITLE
Migrate to BOPTEST-Service as only deployment architecture

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#617]
This issue will migrate [BOPTEST-Service](https://github.com/NREL/boptest-service) to be used as the only deployment architecture and RESTful API.  The primary advantage and reason for this is to alleviate the need to maintain the two closely matched but not exact RESTful APIs, alleviate developers and users having to develop and maintain interfaces for each of them, and generally streamline the implementation of new BOPTEST features which are also supported by BOPTEST-Service.  A downside is that the service architecture is more complex for those who use BOPTEST locally.  However, with continued usage of docker-compose, users will still be able to deploy BOPTEST easily and in the same basic way.  

Todos:
- [x] Migrate BOPTEST-Service code (Service v0.4.0, BOPTEST v0.6.0)
- [x] Fix 400 error response message in Service when wrong point name - see https://github.com/ibpsa/project1-boptest/issues/671.
- [x] Fix Julia example controller variable error, silence docker build
- [x] Pass all BOPTEST unit tests
- [x] Remove javascript example
- [x] Migrate Service-specific unit tests
- [x] Update release notes
- [x] Update README, including README example commands and unit test (if still needed)
- [x] Incorporate lessons-learned from ADRENALIN (logging and timeouts) - see https://github.com/ibpsa/project1-boptest/issues/684.
- [x] Update get_html_IO, find_days, create_ttl to work with Service architecture (see also https://github.com/ibpsa/project1-boptest/issues/700)

**Comment by dhblum** [comment]
@kbenne FYI I've created this issue.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/652.
