### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#701]
This issue is to prep the v0.7.0 release.  Some specific todos:
- [x] Merge PR #708 for pre release
- [ ] Merge PR #710 for post release
- [x] Update UserGuide for Service merge in #617
- [x] Update Website for Service merge in #617

**Comment by dhblum** [comment]
Closed by #708 and #710
